# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class Stock(scrapy.Item):
    n = scrapy.Field()
    ticker = scrapy.Field()
    company = scrapy.Field()
    sector = scrapy.Field()
    industry = scrapy.Field()
    country = scrapy.Field()
    market_cap = scrapy.Field()
    p_e = scrapy.Field()
    price = scrapy.Field()
    change = scrapy.Field()
    volume = scrapy.Field()

class Option(scrapy.Item):
    ticker = scrapy.Field()
    symbol = scrapy.Field()
    option = scrapy.Field()
    close = scrapy.Field()
    change = scrapy.Field()
    volume = scrapy.Field()
    volume_change = scrapy.Field()
    open_interest = scrapy.Field()
    open_interest_change = scrapy.Field()
    url = scrapy.Field()

class YahooSummary(scrapy.Item):
    ticker = scrapy.Field()
    # paste in rest of fields here from output
    forward_annual_dividend_yield = scrapy.Field()
    operating_margin = scrapy.Field()
    net_income_avl_to_common_ttm = scrapy.Field()
    total_debt_equity_mrq = scrapy.Field()
    last_split_factor_new_per_old = scrapy.Field()
    float = scrapy.Field()
    net_assets2 = scrapy.Field()
    _52_week_high = scrapy.Field()
    diluted_eps_ttm = scrapy.Field()
    price_book_mrq = scrapy.Field()
    dividend_date = scrapy.Field()
    short_ratio = scrapy.Field()
    most_recent_quarter_mrq = scrapy.Field()
    short_of_float = scrapy.Field()
    enterprise_value = scrapy.Field()
    eps_ttm = scrapy.Field()
    shares_short = scrapy.Field()
    open = scrapy.Field()
    qtrly_earnings_growth_yoy = scrapy.Field()
    trailing_annual_dividend_yield = scrapy.Field()
    return_on_assets_ttm = scrapy.Field()
    current_ratio_mrq = scrapy.Field()
    ytd_return_mkt_2 = scrapy.Field()
    earnings_date = scrapy.Field()
    last_split_date = scrapy.Field()
    next_earnings_date = scrapy.Field()
    profit_margin = scrapy.Field()
    day_s_range = scrapy.Field()
    price_sales_ttm = scrapy.Field()
    div_yield = scrapy.Field()
    fiscal_year_ends = scrapy.Field()
    avg_vol_10_day = scrapy.Field()
    avg_vol_3_month = scrapy.Field()
    _52wk_range = scrapy.Field()
    held_by_insiders = scrapy.Field()
    revenue_per_share_ttm = scrapy.Field()
    _50_day_moving_average = scrapy.Field()
    market_cap = scrapy.Field()
    enterprise_value_ebitda_ttm = scrapy.Field()
    peg_ratio_5_yr_expected = scrapy.Field()
    levered_free_cash_flow_ttm = scrapy.Field()
    forward_annual_dividend_rate = scrapy.Field()
    bid = scrapy.Field()
    revenue_ttm = scrapy.Field()
    prev_close = scrapy.Field()
    enterprise_value_revenue_ttm = scrapy.Field()
    total_cash_per_share_mrq = scrapy.Field()
    volume = scrapy.Field()
    beta = scrapy.Field()
    _52_week_change = scrapy.Field()
    total_debt_mrq = scrapy.Field()
    p_e_ttm_2 = scrapy.Field()
    return_on_equity_ttm = scrapy.Field()
    ask = scrapy.Field()
    ex_dividend_date = scrapy.Field()
    qtrly_revenue_growth_yoy = scrapy.Field()
    s_p500_52_week_change = scrapy.Field()
    total_cash_mrq = scrapy.Field()
    shares_outstanding = scrapy.Field()
    gross_profit_ttm = scrapy.Field()
    book_value_per_share_mrq = scrapy.Field()
    avg_vol_3m = scrapy.Field()
    _200_day_moving_average = scrapy.Field()
    _52_week_low = scrapy.Field()
    shares_short_prior_month = scrapy.Field()
    held_by_institutions = scrapy.Field()
    trailing_p_e_ttm_intraday = scrapy.Field()
    ebitda_ttm = scrapy.Field()
    p_e_ttm = scrapy.Field()
    _1y_target_est = scrapy.Field()
    operating_cash_flow_ttm = scrapy.Field()
    _5_year_average_dividend_yield = scrapy.Field()
    yield_ttm_2 = scrapy.Field()
    forward_p_e = scrapy.Field()
    nav1 = scrapy.Field()
    payout_ratio = scrapy.Field()
